/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MaintenanceHubUI;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Clipboard;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import MaintenanceHubdata.JobList;
import MaintenanceHubdata.UndoStack;
import mainhub.MaintenanceHub.RepairJob;
/**
 *
 * @author Tiyko
 */
public class JobListPanel extends javax.swing.JPanel {

    /**
     * Creates new form JobListPanel
     */
    
     private JobList jobList;
    private UndoStack undoStack;

    public JobListPanel(JobList jobList, UndoStack undoStack) {
        this.jobList = jobList;
        this.undoStack = undoStack;

        initComponents();
        loadTableData();
        
        jTableJobs.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = jTableJobs.getSelectedRow();
                int col = jTableJobs.getSelectedColumn();

                // Only copy if the user clicked the Job ID column (column 0)
                if (row != -1 && col == 0) {
                    String jobID = jTableJobs.getValueAt(row, 0).toString();
                    copyToClipboard(jobID);
                    JOptionPane.showMessageDialog(null, "Job ID copied: " + jobID);
                }
            }
        });


        // Button actions
        jButtonRefresh.addActionListener(e -> loadTableData());
        jButtonDelete.addActionListener(e -> deleteSelectedJob());
        jButtonUndo.addActionListener(e -> undoLastAction());
    }

    // Load all jobs into the table
    private void loadTableData() {
        DefaultTableModel model = (DefaultTableModel) jTableJobs.getModel();
        model.setRowCount(0);

        for (RepairJob job : jobList.getAllJobs()) {
            model.addRow(new Object[]{
                    job.getJobID(),
                    job.getDevice().getType(),
                    job.getDevice().getOwnerName(),
                    job.getType(),
                    job.getStatus(),
                    job.getCost()
            });
        }
    }

    // Delete selected job
    private void deleteSelectedJob() {
        int row = jTableJobs.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a job to delete.");
            return;
        }

        String jobID = jTableJobs.getValueAt(row, 0).toString();
        RepairJob jobToDelete = null;

        for (RepairJob job : jobList.getAllJobs()) {
            if (job.getJobID().equals(jobID)) {
                jobToDelete = job;
                break;
            }
        }

        if (jobToDelete != null) {
            undoStack.pushDeletedJob(jobToDelete);   // ← store job for undo
            jobList.removeJob(jobToDelete);
            loadTableData();
        }
    }


    private void undoLastAction() {
        RepairJob restored = undoStack.undoDelete();

        if (restored == null) {
            JOptionPane.showMessageDialog(this, "Nothing to undo.");
            return;
        }

        jobList.addJob(restored);
        loadTableData();

        JOptionPane.showMessageDialog(this, "Restored job: " + restored.getJobID());
    }

    private void copyToClipboard(String text) {
        StringSelection selection = new StringSelection(text);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(selection, null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableJobs = new javax.swing.JTable();
        jPanelBottom = new javax.swing.JPanel();
        jButtonRefresh = new javax.swing.JButton();
        jButtonUndo = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();

        jTableJobs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Job ID", "Device Type", "Owner", "Service Type", "Status", "Cost"
            }
        ));
        jScrollPane3.setViewportView(jTableJobs);

        jScrollPane1.setViewportView(jScrollPane3);

        jButtonRefresh.setText("Refresh");

        jButtonUndo.setText("Undo");

        jButtonDelete.setText("Delete");

        javax.swing.GroupLayout jPanelBottomLayout = new javax.swing.GroupLayout(jPanelBottom);
        jPanelBottom.setLayout(jPanelBottomLayout);
        jPanelBottomLayout.setHorizontalGroup(
            jPanelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBottomLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButtonRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButtonDelete)
                .addGap(40, 40, 40)
                .addComponent(jButtonUndo)
                .addGap(33, 33, 33))
        );
        jPanelBottomLayout.setVerticalGroup(
            jPanelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRefresh)
                    .addComponent(jButtonUndo)
                    .addComponent(jButtonDelete)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jPanelBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }


    // Variables declaration
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonUndo;
    private javax.swing.JPanel jPanelBottom;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableJobs;
}
