/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MaintenanceHubUI;

import javax.swing.JPanel;

import MaintenanceHubdata.JobList;
import MaintenanceHubdata.UndoStack;

/**
 *
 * @author Tiyko
 */
public class Mainframe extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Mainframe.class.getName());

    /**
     * Creates new form Mainframe
     */
   // Shared data structures
    private JobList jobList = new JobList();
    private UndoStack undoStack = new UndoStack();

    public Mainframe() {
        initComponents();
        setLocationRelativeTo(null); // center window

        // Load default panel
        showPanel(new CreateJobPanel(jobList, undoStack));

        // Navigation buttons
        jButtonCreateJob.addActionListener(e ->
                showPanel(new CreateJobPanel(jobList, undoStack)));

        jButtonViewJobs.addActionListener(e ->
                showPanel(new JobListPanel(jobList, undoStack)));

        jButtonUpdateJob.addActionListener(e ->
                showPanel(new UpdateJobPanel(jobList, undoStack)));

        jButtonExit.addActionListener(e -> System.exit(0));
    }

    // Method to switch panels
    private void showPanel(JPanel panel) {
        jPanelContent.removeAll();
        jPanelContent.add(panel);
        jPanelContent.revalidate();
        jPanelContent.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelJobs = new javax.swing.JPanel();
        jButtonViewJobs = new javax.swing.JButton();
        jButtonCreateJob = new javax.swing.JButton();
        jButtonUpdateJob = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jPanelContent = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelJobs.setAutoscrolls(true);
        jPanelJobs.setLayout(new javax.swing.BoxLayout(jPanelJobs, javax.swing.BoxLayout.LINE_AXIS));

        jButtonViewJobs.setText("View Jobs");
        jPanelJobs.add(jButtonViewJobs);

        jButtonCreateJob.setText("Create Job");
        jPanelJobs.add(jButtonCreateJob);

        jButtonUpdateJob.setText("Update Job");
        jPanelJobs.add(jButtonUpdateJob);

        jButtonExit.setText("Exit");
        jPanelJobs.add(jButtonExit);

        jPanelContent.setLayout(new java.awt.CardLayout());

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabelTitle.setText("Maintenance System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanelContent, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabelTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jPanelJobs, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelJobs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jPanelContent, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreateJob;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonUpdateJob;
    private javax.swing.JButton jButtonViewJobs;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelJobs;
    // End of variables declaration//GEN-END:variables
}
